name: "Build Bug Report"
description: "Report a bug related to the build process"
labels: ["1. Build", "2. Bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Please provide the following information:**
  - type: input
    id: title
    attributes:
      label: Title
      description: "A brief title for the bug report"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A detailed description of the bug"
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the bug"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "What you expected to happen"
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: "What actually happened"
    validations:
      required: true
  - type: textarea
    id: sample_code
    attributes:
      label: Sample Code or DRAW Tcl Script
      description: "Provide a C++ sample or DRAW Tcl script to reproduce the issue"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Details about your environment (OS, compiler, etc.)"
    validations:
      required: true
  - type: textarea
    id: additional_files
    attributes:
      label: Additional Files
      description: "Attach any additional files that may help in reproducing the issue"