name: "DRAW Bug Report"
description: "Report a bug related to DRAW"
labels: ["1. 2. Bug", "DRAW"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a detailed description of the bug.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug.
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a C++ sample or DRAW Tcl script to reproduce the issue.
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.