name: "DRAW Feature Request"
description: "Request a new feature related to DRAW"
labels: ["1. Enhancement", "DRAW"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a detailed description of the feature request.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the feature request.
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case for the feature.
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Describe the benefits of the feature.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.