name: "Feature Request"
description: "Request a new feature or enhancement for the OCCT"
labels: ["2. Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Please provide the following information:**
  - type: dropdown
    attributes:
      label: Category
      description: "Select the bug category"
      options:
        - Application Framework
        - Build
        - Coding
        - Configuration
        - Data Exchange
        - Documentation
        - DRAW
        - Foundation Classes
        - Mesh
        - Modeling
        - Samples
        - Shape Healing
        - Testing
        - Visualization
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A detailed description of the feature request"
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: "Describe the use case for the feature"
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: "Explain the benefits of the feature"
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Any additional context or information"