// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: polygons.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1002000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "ode.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(dda8c6e1fb4cec50);
CAPNP_DECLARE_SCHEMA(c510eb8f18d7ae57);
CAPNP_DECLARE_SCHEMA(e30fa95132a4326a);
CAPNP_DECLARE_SCHEMA(e2f600f4869636d0);

}  // namespace schemas
}  // namespace capnp


struct Polygon {
  Polygon() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    POLYGON3D,
    POLYGON2D,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(dda8c6e1fb4cec50, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Polygon3D {
  Polygon3D() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c510eb8f18d7ae57, 1, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Polygon2D {
  Polygon2D() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e30fa95132a4326a, 1, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct PolygonFile {
  PolygonFile() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e2f600f4869636d0, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Polygon::Reader {
public:
  typedef Polygon Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline  ::uint32_t getIndex() const;

  inline bool isPolygon3d() const;
  inline bool hasPolygon3d() const;
  inline  ::Polygon3D::Reader getPolygon3d() const;

  inline bool isPolygon2d() const;
  inline bool hasPolygon2d() const;
  inline  ::Polygon2D::Reader getPolygon2d() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Polygon::Builder {
public:
  typedef Polygon Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline  ::uint32_t getIndex();
  inline void setIndex( ::uint32_t value);

  inline bool isPolygon3d();
  inline bool hasPolygon3d();
  inline  ::Polygon3D::Builder getPolygon3d();
  inline void setPolygon3d( ::Polygon3D::Reader value);
  inline  ::Polygon3D::Builder initPolygon3d();
  inline void adoptPolygon3d(::capnp::Orphan< ::Polygon3D>&& value);
  inline ::capnp::Orphan< ::Polygon3D> disownPolygon3d();

  inline bool isPolygon2d();
  inline bool hasPolygon2d();
  inline  ::Polygon2D::Builder getPolygon2d();
  inline void setPolygon2d( ::Polygon2D::Reader value);
  inline  ::Polygon2D::Builder initPolygon2d();
  inline void adoptPolygon2d(::capnp::Orphan< ::Polygon2D>&& value);
  inline ::capnp::Orphan< ::Polygon2D> disownPolygon2d();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Polygon::Pipeline {
public:
  typedef Polygon Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Polygon3D::Reader {
public:
  typedef Polygon3D Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasNodes() const;
  inline  ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Reader getNodes() const;

  inline bool hasParameters() const;
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader getParameters() const;

  inline double getDeflection() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Polygon3D::Builder {
public:
  typedef Polygon3D Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasNodes();
  inline  ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Builder getNodes();
  inline void setNodes( ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Builder initNodes(unsigned int size);
  inline void adoptNodes(::capnp::Orphan< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>> disownNodes();

  inline bool hasParameters();
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder getParameters();
  inline void setParameters( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setParameters(::kj::ArrayPtr<const double> value);
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder initParameters(unsigned int size);
  inline void adoptParameters(::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> disownParameters();

  inline double getDeflection();
  inline void setDeflection(double value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Polygon3D::Pipeline {
public:
  typedef Polygon3D Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Polygon2D::Reader {
public:
  typedef Polygon2D Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasNodes() const;
  inline  ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Reader getNodes() const;

  inline bool hasParameters() const;
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader getParameters() const;

  inline double getDeflection() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Polygon2D::Builder {
public:
  typedef Polygon2D Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasNodes();
  inline  ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Builder getNodes();
  inline void setNodes( ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Builder initNodes(unsigned int size);
  inline void adoptNodes(::capnp::Orphan< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>> disownNodes();

  inline bool hasParameters();
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder getParameters();
  inline void setParameters( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setParameters(::kj::ArrayPtr<const double> value);
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder initParameters(unsigned int size);
  inline void adoptParameters(::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> disownParameters();

  inline double getDeflection();
  inline void setDeflection(double value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Polygon2D::Pipeline {
public:
  typedef Polygon2D Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class PolygonFile::Reader {
public:
  typedef PolygonFile Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasPolygons() const;
  inline  ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Reader getPolygons() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PolygonFile::Builder {
public:
  typedef PolygonFile Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasPolygons();
  inline  ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Builder getPolygons();
  inline void setPolygons( ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Builder initPolygons(unsigned int size);
  inline void adoptPolygons(::capnp::Orphan< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>> disownPolygons();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PolygonFile::Pipeline {
public:
  typedef PolygonFile Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::Polygon::Which Polygon::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline  ::Polygon::Which Polygon::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Polygon::Reader::getIndex() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Polygon::Builder::getIndex() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Polygon::Builder::setIndex( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Polygon::Reader::isPolygon3d() const {
  return which() == Polygon::POLYGON3D;
}
inline bool Polygon::Builder::isPolygon3d() {
  return which() == Polygon::POLYGON3D;
}
inline bool Polygon::Reader::hasPolygon3d() const {
  if (which() != Polygon::POLYGON3D) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Polygon::Builder::hasPolygon3d() {
  if (which() != Polygon::POLYGON3D) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Polygon3D::Reader Polygon::Reader::getPolygon3d() const {
  KJ_IREQUIRE((which() == Polygon::POLYGON3D),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Polygon3D>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Polygon3D::Builder Polygon::Builder::getPolygon3d() {
  KJ_IREQUIRE((which() == Polygon::POLYGON3D),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Polygon3D>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Polygon::Builder::setPolygon3d( ::Polygon3D::Reader value) {
  _builder.setDataField<Polygon::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Polygon::POLYGON3D);
  ::capnp::_::PointerHelpers< ::Polygon3D>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Polygon3D::Builder Polygon::Builder::initPolygon3d() {
  _builder.setDataField<Polygon::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Polygon::POLYGON3D);
  return ::capnp::_::PointerHelpers< ::Polygon3D>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Polygon::Builder::adoptPolygon3d(
    ::capnp::Orphan< ::Polygon3D>&& value) {
  _builder.setDataField<Polygon::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Polygon::POLYGON3D);
  ::capnp::_::PointerHelpers< ::Polygon3D>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Polygon3D> Polygon::Builder::disownPolygon3d() {
  KJ_IREQUIRE((which() == Polygon::POLYGON3D),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Polygon3D>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Polygon::Reader::isPolygon2d() const {
  return which() == Polygon::POLYGON2D;
}
inline bool Polygon::Builder::isPolygon2d() {
  return which() == Polygon::POLYGON2D;
}
inline bool Polygon::Reader::hasPolygon2d() const {
  if (which() != Polygon::POLYGON2D) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Polygon::Builder::hasPolygon2d() {
  if (which() != Polygon::POLYGON2D) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Polygon2D::Reader Polygon::Reader::getPolygon2d() const {
  KJ_IREQUIRE((which() == Polygon::POLYGON2D),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Polygon2D>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Polygon2D::Builder Polygon::Builder::getPolygon2d() {
  KJ_IREQUIRE((which() == Polygon::POLYGON2D),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Polygon2D>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Polygon::Builder::setPolygon2d( ::Polygon2D::Reader value) {
  _builder.setDataField<Polygon::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Polygon::POLYGON2D);
  ::capnp::_::PointerHelpers< ::Polygon2D>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Polygon2D::Builder Polygon::Builder::initPolygon2d() {
  _builder.setDataField<Polygon::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Polygon::POLYGON2D);
  return ::capnp::_::PointerHelpers< ::Polygon2D>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Polygon::Builder::adoptPolygon2d(
    ::capnp::Orphan< ::Polygon2D>&& value) {
  _builder.setDataField<Polygon::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Polygon::POLYGON2D);
  ::capnp::_::PointerHelpers< ::Polygon2D>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Polygon2D> Polygon::Builder::disownPolygon2d() {
  KJ_IREQUIRE((which() == Polygon::POLYGON2D),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Polygon2D>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Polygon3D::Reader::hasNodes() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Polygon3D::Builder::hasNodes() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Reader Polygon3D::Reader::getNodes() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Builder Polygon3D::Builder::getNodes() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Polygon3D::Builder::setNodes( ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>::Builder Polygon3D::Builder::initNodes(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Polygon3D::Builder::adoptNodes(
    ::capnp::Orphan< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>> Polygon3D::Builder::disownNodes() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec3,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Polygon3D::Reader::hasParameters() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Polygon3D::Builder::hasParameters() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader Polygon3D::Reader::getParameters() const {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Polygon3D::Builder::getParameters() {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Polygon3D::Builder::setParameters( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline void Polygon3D::Builder::setParameters(::kj::ArrayPtr<const double> value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Polygon3D::Builder::initParameters(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Polygon3D::Builder::adoptParameters(
    ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> Polygon3D::Builder::disownParameters() {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline double Polygon3D::Reader::getDeflection() const {
  return _reader.getDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline double Polygon3D::Builder::getDeflection() {
  return _builder.getDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Polygon3D::Builder::setDeflection(double value) {
  _builder.setDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Polygon2D::Reader::hasNodes() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Polygon2D::Builder::hasNodes() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Reader Polygon2D::Reader::getNodes() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Builder Polygon2D::Builder::getNodes() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Polygon2D::Builder::setNodes( ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>::Builder Polygon2D::Builder::initNodes(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Polygon2D::Builder::adoptNodes(
    ::capnp::Orphan< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>> Polygon2D::Builder::disownNodes() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Vec2,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Polygon2D::Reader::hasParameters() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Polygon2D::Builder::hasParameters() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader Polygon2D::Reader::getParameters() const {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Polygon2D::Builder::getParameters() {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Polygon2D::Builder::setParameters( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline void Polygon2D::Builder::setParameters(::kj::ArrayPtr<const double> value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Polygon2D::Builder::initParameters(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Polygon2D::Builder::adoptParameters(
    ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> Polygon2D::Builder::disownParameters() {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline double Polygon2D::Reader::getDeflection() const {
  return _reader.getDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline double Polygon2D::Builder::getDeflection() {
  return _builder.getDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Polygon2D::Builder::setDeflection(double value) {
  _builder.setDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool PolygonFile::Reader::hasPolygons() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool PolygonFile::Builder::hasPolygons() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Reader PolygonFile::Reader::getPolygons() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Builder PolygonFile::Builder::getPolygons() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void PolygonFile::Builder::setPolygons( ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>::Builder PolygonFile::Builder::initPolygons(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void PolygonFile::Builder::adoptPolygons(
    ::capnp::Orphan< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>> PolygonFile::Builder::disownPolygons() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Polygon,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}


CAPNP_END_HEADER

