# Source files for math package
set(OCCT_math_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_math_FILES
  math.cxx
  math.hxx
  math_Array1OfValueAndWeight.hxx
  math_BFGS.cxx
  math_BFGS.hxx
  math_BFGS.lxx
  math_BissecNewton.cxx
  math_BissecNewton.hxx
  math_BissecNewton.lxx
  math_BracketedRoot.cxx
  math_BracketedRoot.hxx
  math_BracketedRoot.lxx
  math_BracketMinimum.cxx
  math_BracketMinimum.hxx
  math_BracketMinimum.lxx
  math_BrentMinimum.cxx
  math_BrentMinimum.hxx
  math_BrentMinimum.lxx
  math_BullardGenerator.hxx
  math_ComputeGaussPointsAndWeights.cxx
  math_ComputeGaussPointsAndWeights.hxx
  math_ComputeKronrodPointsAndWeights.cxx
  math_ComputeKronrodPointsAndWeights.hxx
  math_Crout.cxx
  math_Crout.hxx
  math_Crout.lxx
  math_DirectPolynomialRoots.cxx
  math_DirectPolynomialRoots.hxx
  math_DoubleTab.hxx
  math_EigenValuesSearcher.cxx
  math_EigenValuesSearcher.hxx
  math_FRPR.cxx
  math_FRPR.hxx
  math_FRPR.lxx
  math_Function.cxx
  math_Function.hxx
  math_FunctionAllRoots.cxx
  math_FunctionAllRoots.hxx
  math_FunctionAllRoots.lxx
  math_FunctionRoot.cxx
  math_FunctionRoot.hxx
  math_FunctionRoot.lxx
  math_FunctionRoots.cxx
  math_FunctionRoots.hxx
  math_FunctionRoots.lxx
  math_FunctionSample.cxx
  math_FunctionSample.hxx
  math_FunctionSet.cxx
  math_FunctionSet.hxx
  math_FunctionSetRoot.cxx
  math_FunctionSetRoot.hxx
  math_FunctionSetWithDerivatives.hxx
  math_FunctionWithDerivative.cxx
  math_FunctionWithDerivative.hxx
  math_Gauss.cxx
  math_Gauss.hxx
  math_GaussLeastSquare.cxx
  math_GaussLeastSquare.hxx
  math_GaussLeastSquare.lxx
  math_GaussMultipleIntegration.cxx
  math_GaussMultipleIntegration.hxx
  math_GaussMultipleIntegration.lxx
  math_GaussSetIntegration.cxx
  math_GaussSetIntegration.hxx
  math_GaussSetIntegration.lxx
  math_GaussSingleIntegration.cxx
  math_GaussSingleIntegration.hxx
  math_GaussSingleIntegration.lxx
  math_GlobOptMin.cxx
  math_GlobOptMin.hxx
  math_Householder.cxx
  math_Householder.hxx
  math_Householder.lxx
  math_IntegerVector.hxx
  math_Jacobi.cxx
  math_Jacobi.hxx
  math_Jacobi.lxx
  math_Kronrod.cxx
  math_KronrodSingleIntegration.cxx
  math_KronrodSingleIntegration.hxx
  math_KronrodSingleIntegration.lxx
  math_Matrix.cxx
  math_Matrix.hxx
  math_Matrix.lxx
  math_MultipleVarFunction.cxx
  math_MultipleVarFunction.hxx
  math_MultipleVarFunctionWithGradient.hxx
  math_MultipleVarFunctionWithHessian.hxx
  math_NewtonFunctionRoot.cxx
  math_NewtonFunctionRoot.hxx
  math_NewtonFunctionRoot.lxx
  math_NewtonFunctionSetRoot.cxx
  math_NewtonFunctionSetRoot.hxx
  math_NewtonFunctionSetRoot.lxx
  math_NewtonMinimum.cxx
  math_NewtonMinimum.hxx
  math_NewtonMinimum.lxx
  math_NotSquare.hxx
  math_Powell.cxx
  math_Powell.hxx
  math_Powell.lxx
  math_PSO.cxx
  math_PSO.hxx
  math_PSOParticlesPool.cxx
  math_PSOParticlesPool.hxx
  math_Recipes.cxx
  math_Recipes.hxx
  math_SingularMatrix.hxx
  math_Status.hxx
  math_SVD.cxx
  math_SVD.hxx
  math_SVD.lxx
  math_TrigonometricFunctionRoots.cxx
  math_TrigonometricFunctionRoots.hxx
  math_TrigonometricFunctionRoots.lxx
  math_TrigonometricEquationFunction.hxx
  math_Uzawa.cxx
  math_Uzawa.hxx
  math_Uzawa.lxx
  math_ValueAndWeight.hxx
  math_VectorBase.hxx
  math_VectorBase.lxx
  math_Vector.hxx
  # New modern math solver API (C++17 template-based)
  # Types and configuration
  math_Types.hxx
  math_Config.hxx
  # Internal utilities
  math_InternalCore.hxx
  math_InternalConvergence.hxx
  math_InternalPoly.hxx
  math_InternalBracket.hxx
  math_InternalGauss.hxx
  math_InternalDeriv.hxx
  math_InternalLineSearch.hxx
  math_GaussKronrodWeights.hxx
  math_GaussKronrodWeights.cxx
  # Polynomial root solvers
  math_Poly.hxx
  math_Poly_Quadratic.hxx
  math_Poly_Cubic.hxx
  math_Poly_Quartic.hxx
  # Root finding algorithms
  math_Roots.hxx
  math_Roots_Newton.hxx
  math_Roots_Brent.hxx
  math_Roots_Bisection.hxx
  math_Roots_Secant.hxx
  math_Roots_Multiple.hxx
  # Minimization algorithms (1D and N-D)
  math_Min.hxx
  math_Min_Brent.hxx
  math_Min_Powell.hxx
  math_Min_BFGS.hxx
  math_Min_FRPR.hxx
  math_Min_Newton.hxx
  math_Min_PSO.hxx
  math_Min_GlobOpt.hxx
  # Integration algorithms
  math_Integ.hxx
  math_Integ_Gauss.hxx
  math_Integ_Kronrod.hxx
  math_Integ_DoubleExp.hxx
  # Linear algebra algorithms
  math_Lin.hxx
  math_Lin_Gauss.hxx
  math_Lin_SVD.hxx
  math_Lin_Householder.hxx
  math_Lin_Jacobi.hxx
  math_Lin_LeastSquares.hxx
  # Nonlinear systems solvers
  math_Sys.hxx
  math_Sys_Newton.hxx
  math_Sys_LevenbergMarquardt.hxx
  # Non-virtual functors
  math_Functor.hxx
  math_Functor_Scalar.hxx
  math_Functor_Vector.hxx
)
