name: Build OCCT on Windows with MSVC x64 dynamic

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-windows-msvc:
    name: Build on Windows with MSVC
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install magicsplat-tcl-tk -y

    - name: Configure OCCT
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019"
              -T host=x64
              -D USE_FREETYPE=OFF
              -D CMAKE_BUILD_TYPE=Release ..

    - name: Build OCCT
      run: |
        cd build
        cmake --build . --config Release -- /m
