# This workflow builds OCCT on macOS with Clang x64 dynamic.
#
# Notes:
# freetype is disabled
# samples are not built

name: Build OCCT on macOS with Clang x64 dynamic

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-macos-clang:
    name: Build on macOS with Clang
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Install dependencies
      run: |
        brew update
        brew install tcl-tk tbb gl2ps xerces-c \
                     libxmu libxi libxft libxpm \
                     glew

    - name: Configure OCCT
      run: |
        mkdir -p build
        cd build
        cmake -G "Unix Makefiles" \
              -D CMAKE_C_COMPILER=clang \
              -D CMAKE_CXX_COMPILER=clang++ \
              -D USE_FREETYPE=OFF \
              -D BUILD_USE_PCH=ON \
              -D BUILD_INCLUDE_SYMLINK=ON \
              -D CMAKE_BUILD_TYPE=Release ..

    - name: Build OCCT
      run: |
        cd build
        make -j$(sysctl -n hw.logicalcpu)

    - name: Dowload test data
      run: |
        cd data
        curl -L -O https://github.com/Open-Cascade-SAS/OCCT/releases/download/V7_8_0/opencascade-dataset-7.8.0.tar.xz
        tar -xf opencascade-dataset-7.8.0.tar.xz

    - name: Run tests
      run: |
         cd build
         source env.sh
         DRAWEXE -v -c testgrid boolean volumemaker E1

    - name: Upload test results
      uses: actions/upload-artifact@v4.4.3
      id: artifact-upload-step
      with:
        name: results
        path: build/results
        retention-days: 7
