# This workflow will build OCCT on Windows with MSVC x64 in dynamic mode
# using the provided Docker image with MSVC tools.
#
# Notes:
# freetype is disabled
# Draw module is disabled
# samples are not built

name: Build OCCT on Windows with MSVC x64 dynamic

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-windows-msvc:
    name: Build on Windows with MSVC
    runs-on: windows-2022
    concurrency:
      group: ${{ github.workflow }}-build-windows-msvc-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x64

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install magicsplat-tcl-tk -y

    - name: Configure OCCT
      run: |
          mkdir build
          cd build
          cmake -T host=x64 -D USE_FREETYPE=OFF -D BUILD_USE_PCH=ON -D BUILD_OPT_PROFILE=Production -D BUILD_INCLUDE_SYMLINK=ON -D BUILD_MODULE_Draw=OFF -D CMAKE_BUILD_TYPE=Release ..
  
    - name: Build OCCT
      run: |
          cd build
          cmake --build . --config Release -- /m

    - name: Download and extract test data
      run: |
        cd data
        Invoke-WebRequest -Uri https://github.com/Open-Cascade-SAS/OCCT/releases/download/V7_8_0/opencascade-dataset-7.8.0.zip -OutFile opencascade-dataset-7.8.0.zip
        Expand-Archive -Path opencascade-dataset-7.8.0.zip -DestinationPath .
        Remove-Item opencascade-dataset-7.8.0.zip
      shell: pwsh

    - name: Run tests
      run: |
        cd build
        dir
        call env.bat vc14 win64 release
        DRAWEXE.exe -v -c testgrid
      shell: cmd

    - name: Upload test results
      uses: actions/upload-artifact@v4.4.3
      id: artifact-upload-step
      with:
        name: results
        path: build/results
        retention-days: 7
