# This workflow builds the OCCT reference manual documentation.
# It is triggered on pushes to the 'master' branch.
# The workflow includes steps to checkout the repository, install dependencies, build the documentation, and upload the generated documentation and logs as artifacts.

name: Build Documentation

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build Refman Documentation
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1

    - name: Install dependencies
      run: |
        choco install -y graphviz
        choco install -y doxygen.install

    - name: Build documentation
      run: |
        set PATH=%PATH%;C:\Program Files\doxygen\bin;C:\Program Files\Graphviz\bin;C:\Program Files\doxygen
        cd adm
        bash gendoc -refman
      shell: cmd

    - name: Upload refman documentation
      uses: actions/upload-artifact@v4.4.3
      id: artifact-upload-step
      with:
        name: refman-doc
        path: doc/refman
        retention-days: 90

    - name: Upload generation log
      uses: actions/upload-artifact@v4.4.3
      with:
        name: doxygen.log
        path: doc/html_doxygen_err.log
        retention-days: 90
